image: alpine:latest

stages:
  - build

include:
  - ".gitlab/*.yaml"

pages:
  stage: build
  script:
    - echo "deploying to pages"
  artifacts:
    paths:
      - site
  rules:
    - if: $CI_COMMIT_BRANCH == "master" && $TASK == "pages" && $CI_PIPELINE_SOURCE =~ /^(schedule|web|trigger)$/
