on:
  repository_dispatch:
    types: [add_module]

jobs:
  addmodule:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v5
      - run: |
          url="${{ github.event.client_payload.url }}"
          id="$(echo $url | sed 's|.*b.com/||g')"
          maintainer="${id%/*}"
          name="${id##*/}"
          maintainerURL="${url%/*}"
          category="${{ github.event.client_payload.category }}"
          description="${{ github.event.client_payload.description }}"
          echo "======================================================"
          set | grep -E "name=|category=|url=|id=|maintainer=|maintainerURL=|description="
          echo "======================================================"
          jqurl="$(curl -s https://api.github.com/repos/itchyny/gojq/releases/latest | sed -rn 's|.*browser_download_url": "(.*amd64.tar.gz)".*|\1|p')"
          curl -sL --output gojq.tar.gz "$jqurl"
          tar -zxf gojq.tar.gz
          cp ./gojq_*/gojq /usr/local/bin/
          json="$(cat module.json \
            | gojq '.name |= "'"$name"'"' \
            | gojq '.category |= "'"$category"'"' \
            | gojq '.url |= "'"$url"'"' \
            | gojq '.id |= "'"$id"'"' \
            | gojq '.maintainer |= "'"$maintainer"'"' \
            | gojq '.maintainerURL |= "'"$maintainerURL"'"' \
            | gojq '.description |= "'"$description"'"' \
            )"
          echo "$json"
          status="$(curl -s -o /dev/null -w "%{http_code}" "$url")"
          if [ "$status" -lt "400" ]; then
            echo "url o.k."
          else
            echo "url responds with status code $status"
            exit 1
          fi
