on:
  repository_dispatch:
    types: [add_module]

jobs:
  addmodule:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v5
      - run: |
          url="${{ github.event.client_payload.url }}"
          id="$(echo $url | sed 's|.*b.com/||g')"
          maintainer="${id%/*}"
          name="${id##*/}"
          maintainerURL="${url%/*}"
          category="${{ github.event.client_payload.category }}"
          description="${{ github.event.client_payload.description }}"
          echo "======================================================"
          set | grep -E "name=|category=|url=|id=|maintainer=|maintainerURL=|description="
          echo "======================================================"
          sudo apt-get update
          sudo apt-get install -y jq
          json="$(cat module.json \
            | jq '.name |= "'"$name"'"' \
            | jq '.category |= "'"$category"'"' \
            | jq '.url |= "'"$url"'"' \
            | jq '.id |= "'"$id"'"' \
            | jq '.maintainer |= "'"$maintainer"'"' \
            | jq '.maintainerURL |= "'"$maintainerURL"'"' \
            | jq '.description |= "'"$description"'"' \
            )"
          echo "$json"
          status="$(curl -s -o /dev/null -w "%{http_code}" "$url")"
          if [ "$status" -lt "400" ]; then
            echo "url o.k."
          else
            echo "url responds with status code $status"
            exit 1
          fi
          jq --argjson p "$json" '.modules += [$p]' modules.stage.1.json > modules.stage.1.json
          git status
