on:
  repository_dispatch:
    types: [add_module]

permissions:
  contents: write

jobs:
  addmodule:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v5
      - run: |
          url="${{ github.event.client_payload.url }}"
          id="$(echo $url | sed 's|.*b.com/||g')"
          maintainer="${id%/*}"
          name="${id##*/}"
          maintainerURL="${url%/*}"
          category="${{ github.event.client_payload.category }}"
          description="${{ github.event.client_payload.description }}"
          echo "======================================================"
          set | grep -E "name=|category=|url=|id=|maintainer=|maintainerURL=|description="
          echo "======================================================"
          sudo apt-get update
          sudo apt-get install -y jq
          json="$(cat module.json \
            | jq '.name |= "'"$name"'"' \
            | jq '.category |= "'"$category"'"' \
            | jq '.url |= "'"$url"'"' \
            | jq '.id |= "'"$id"'"' \
            | jq '.maintainer |= "'"$maintainer"'"' \
            | jq '.maintainerURL |= "'"$maintainerURL"'"' \
            | jq '.description |= "'"$description"'"' \
            )"
          echo "$json"
          status="$(curl -s -o /dev/null -w "%{http_code}" "$url")"
          if [ "$status" -lt "400" ]; then
            echo "url o.k."
          else
            echo "url responds with status code $status"
            exit 1
          fi
          existurl="$(jq -r '.modules[] | select(.url=="'$url'") | .url' modules.stage.1.json)"
          if [[ -n "$existurl" ]]; then
            echo "url $url exists already"
            exit 1
          fi
          git config --global user.email "you@example.com"
          git config --global user.name "auto-add-module"
          newcontent="$(jq --argjson p "$json" '.modules += [$p]' modules.stage.1.json)"
          echo "$newcontent" > modules.stage.1.json
          git diff
          git add modules.stage.1.json
          git commit -m "add new module $url"
          git push $GITHUB_SERVER_URL/$GITHUB_REPOSITORY HEAD:master
